//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItensPedido
    {
        public int ID_ItensPedido { get; set; }
        public Nullable<int> ID_ItensProduto { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<decimal> Valor_Total { get; set; }
        public Nullable<int> ID_PedidosPed { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
